
import type { Metadata } from "next";


import BentoGridDemo from "@/Components/Projects";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mt-35 h-[300vh] md:h-[100vh] lg:h-[90vh] md:mb-35">
        <div >
            <div>
                <BentoGridDemo/>
            </div>
            
        </div>
        {children}
    </div>

  );
}
