import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BentoGridDemo from "@/Components/Projects";

const inter = Inter({ subsets: ["latin"] }); // Correct way to define font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className={inter.className}>
      <div className="mt-35 h-[220vh] md:h-[100vh] lg:h-[90vh] md:mb-35">
        <BentoGridDemo />
      </div>
      {children}
    </div>
  );
}
