import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import CardHoverEffectDemo from "@/Components/Skillcard";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className="mt-34">
          <h2
            className="text-5xl font-extrabold tracking-wide uppercase mt-10 mb-6 
    bg-gradient-to-r from-blue-500 via-green-500 to-purple-500 text-transparent bg-clip-text text-center"
          >
            My Technical Skills
          </h2>

          <div>
            <CardHoverEffectDemo />
          </div>
          {children}
        </div>
      
  );
}
