import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar"
import Footer from "@/Components/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className={`Inter.className`} >
      
      <body >
        <div className="nav">
        <Navbar/>
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
